### ISSUE TITLE
Add Location on jobs

### ISSUE THREAD

**Issue by guillemc23** [getmanfred/mac#10]
It would be cool to add an optional location field for studies and jobs in the CV and in the Manfred site.
Maybe the user could type a city and a country from a list and the flag could be represented via its ISO country code using the [flagpedia](https://flagpedia.net/download/api) API. 

Something like:
```json
location: {
     city: "Paris",
     country: "FR"
}

```
Keep up this awesome project!

**Comment by ydarias** [comment]
Actually, jobs and studies are linked to another def `publicEntityDetails` that contains a `location`. At `location` you can define the country with ISO code.
