### ISSUE TITLE
Modifique mi json, hice commit y push y no se actualizó enla web. I modifed my json, commited and pushed and the change wasn't displayed on the web page.

### ISSUE THREAD

**Issue by salluzziluca** [getmanfred/mac#18]
I modified a single word, "habilites " to "abilities". The commit is shown on my remote here in GitHub but the change isn't displayed on the webpage. 
- [mi repo](https://github.com/salluzziluca/CV)
- [la web](https://www.getmanfred.com/profile/salluzziluca)

**Comment by dbonillaf** [comment]
Thanks Luca! We are going to investigate why the aboutme/profile/description didn't sync.
@ydarias will be in top of that.

**Comment by ydarias** [comment]
Hello @salluzziluca we are working on it :-)

**Comment by salluzziluca** [comment]
Understood. I received the email but when I check my json with the schema it just validates. 
![image](https://user-images.githubusercontent.com/63552496/163904919-9c103ffe-f55b-4e4e-9ca7-e8343e95524c.png)

(I took that screenshot just now, I ctrl+A from my repo, last commit being 44b6936, and ctrl+A del ctrl+v on the web page validator)

**Comment by ydarias** [comment]
That's strange, for the last commit from your repository we get that the JSON is not compliant with the MAC JSON Schema. The error is the one described before, related to a URL with an empty string as its value.

Are you sure you are using [the schema at this repo](https://github.com/getmanfred/mac/blob/master/schema/schema.json)? Because some of the text in that JSON Schema doesn't appear in our schema.

**Comment by salluzziluca** [comment]
Sorry! I was using a wrong schema sample. Now it shows me the two errors
![image](https://user-images.githubusercontent.com/63552496/164059335-f40757d5-edd3-4e98-a170-47e177ab5578.png)

**Comment by ydarias** [comment]
It is fine, don't worry :-)

We are preparing the fix to prevent Manfred from generating an invalid JSON. When it is ready, you will be able to export to Github again and it should be fixed.

**Comment by ydarias** [comment]
Hello @salluzziluca, sorry I didn't contact you before, too many repositories 🤦‍♀️ 

We launched in production some changes that should fix this behavior. You just need to:
1. Update your profile at Manfred (it is required some change) :-( 
2. The system will push the changes again to Github automatically
3. At this point you should be able to change at Github and visualize the changes at Manfred again.

Really sorry for the difficulties.

And thank you very much for the testing and information, very valuable.
