### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by brauliodiez** [getmanfred/mac#4]
I think it would be a good idea to add TypeScript definitions we could just add a subfolder, named _TypeScript_ and developers who are using this technology can get benefit of deinition types.

I have used a tool to extract the typings from the schema definition and generated a codesandbox:

[codesandbox example](https://codesandbox.io/s/hidden-currying-thvfcn)

This example, just use the typescript definition and is tested agains the example cv you provide:

- _model.ts_: automated typescript definition.
- _cv-sample_: example data (try to remove any of the fields and you will get a red warning)
- _index.ts_: just dumps the content of the CV in the console.

If you think this can be interesting, gimme a buzz we can fork the project and:
  - First add the definition to the project (we could offer two flavours model like and defintion type (d.ts)
  - We could create a Github Actions so whenever a merge to master (or other branch) is performed a simple nodejs tool could be launched and the definition types could be automatically updated.

**Comment by brauliodiez** [comment]
Hello @dbonillaf  and @ydarias sorry we started working on this case before it was assigned, we have created a first version, could you take a look to the PR? Thanks

**Comment by ydarias** [comment]
Don't worry @brauliodiez this is open source, so PRs are welcome. I will take a look to the PR you created :-) Thank you in advance ^_^
