### ISSUE TITLE
Possible adoption of this schema as standardized schema in Smart Data Models

### ISSUE THREAD

**Issue by albertoabellagarcia** [getmanfred/mac#41]
The [Smart Data Models initiative](https://smartdatamodels.org) compiles open-licensed reference data models based on real experiences. 
We would like to map this schema of a CV.  Once adopted we create automatically specifications in 8 languages (EN, FR, DE, SP, IT, JA, ZH, KO), exports in SQL, yaml, etc and also examples in csv, etc. 
In order to do that we need an example we will take from the samples section here but also to attribute to all the authors. 
Should I take as authors all listed in [Contributors](https://github.com/getmanfred/mac/graphs/contributors) ?

**Comment by ydarias** [comment]
Hello @albertoabellagarcia 

yes, you can take the people listed on the Contributors page. And good luck with the initiative, if you need something don't hesitate to ask.
